In [ ]:
import numpy as np

# 1. numpy로 5x5 랜덤 행렬 만들기

In [4]:
a=np.random.random((5,5))
print(a)

[[0.27256445 0.98917995 0.07114072 0.79926405 0.23969014]
 [0.80478659 0.09748369 0.7503959  0.03095843 0.05164492]
 [0.13663289 0.14028369 0.78751947 0.72739145 0.79974777]
 [0.40468762 0.22329369 0.75673081 0.29983754 0.81019219]
 [0.9097251  0.24756749 0.27425579 0.98508658 0.37157529]]


# 2.1 1에서 만든 행렬 각 행의 최대값 구하기

In [5]:
a.max(1)

array([0.98917995, 0.80478659, 0.79974777, 0.81019219, 0.98508658])

# 2.2 1에서 만든 행렬 각 열의 최대값 구하기

In [6]:
a.max(0)

array([0.9097251 , 0.98917995, 0.78751947, 0.98508658, 0.81019219])

# 2.3 1에서 만든 행렬 전체의 최대값 구하기

In [7]:
a.max()

0.9891799457333734

# 3. 5x5 에서 가운데 3x3 구하기

In [8]:
b=a[1:4,1:4]
print(b)

[[0.09748369 0.7503959  0.03095843]
 [0.14028369 0.78751947 0.72739145]
 [0.22329369 0.75673081 0.29983754]]


# 4.1 1에서 만든 5x5 행렬을 1차원 벡터로 만들기

In [12]:
b = a.flatten()
print(b)

[0.27256445 0.98917995 0.07114072 0.79926405 0.23969014 0.80478659
 0.09748369 0.7503959  0.03095843 0.05164492 0.13663289 0.14028369
 0.78751947 0.72739145 0.79974777 0.40468762 0.22329369 0.75673081
 0.29983754 0.81019219 0.9097251  0.24756749 0.27425579 0.98508658
 0.37157529]


# 4.2 1에서 만든 5x5 행렬을 1x25 행렬로 만들기

In [13]:
a.reshape(1,25)

array([[0.27256445, 0.98917995, 0.07114072, 0.79926405, 0.23969014,
        0.80478659, 0.09748369, 0.7503959 , 0.03095843, 0.05164492,
        0.13663289, 0.14028369, 0.78751947, 0.72739145, 0.79974777,
        0.40468762, 0.22329369, 0.75673081, 0.29983754, 0.81019219,
        0.9097251 , 0.24756749, 0.27425579, 0.98508658, 0.37157529]])